### ISSUE TITLE
Can k3s or kind be used?

### ISSUE THREAD

**Issue by dbit-xia** [soketi/network-watcher#155]
soketi.yaml 
```
- name: network-watcher
          image: quay.io/soketi/network-watcher:6.3
          env:
            - name: KUBE_CONNECTION
              value: cluster
            - name: MEMORY_PERCENT
              value: "75" # if > 75% memory, reject new connections
            - name: CHECKING_INTERVAL
              value: "5" # every 5 seconds
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
```
automatically quit after kubectl apply, 
show  log 
```
root@kind-control-plane:/# kubectl logs soketi-65d8574fd7-7st8f -c network-watcher
Interactive shell
php >
```
